/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uam.patrones.proyecto.formas;


import java.util.ArrayList;
import java.util.List;
import java.sql.*;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import uam.patrones.proyecto.clases.LineaDeVenta;
import uam.patrones.proyecto.clases.Producto;
import uam.patrones.proyecto.operaciones.EstrategiaDescuentoSobreUmbral;
import uam.patrones.proyecto.operaciones.EstrategiaPreciosVenta;
import uam.patrones.proyecto.operaciones.UtileriaLineaVenta;
import static uam.patrones.proyecto.operaciones.UtileriaLineaVenta.imprimeListaProducto;
import uam.patrones.proyecto.operaciones.Venta;
import uam.patrones.proyecto.operaciones.conexionBD;


/**
 *
 * @author ELI ZACARIAS
 */
public class AltasProductosFrm extends javax.swing.JFrame {
    
    
    
    conexionBD con = new conexionBD();
    Connection cn= con.conexion();

    /**
     * Creates new form Principal
     */
    public AltasProductosFrm() {
        initComponents();
        
        Iniciar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        sclProductos = new javax.swing.JScrollPane();
        txtResultados = new javax.swing.JTextArea();
        btnRegresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblProducto = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox<>();
        lblMarca = new javax.swing.JLabel();
        lblTalla = new javax.swing.JLabel();
        cmbMarca = new javax.swing.JComboBox<>();
        cmbTalla = new javax.swing.JComboBox<>();
        btnAgregarProducto = new javax.swing.JButton();
        txtProducto = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        lblBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo.setText("Producto      Precio             Categoria      Marca          Talla     ");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        sclProductos.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N

        txtResultados.setColumns(20);
        txtResultados.setRows(5);
        sclProductos.setViewportView(txtResultados);

        getContentPane().add(sclProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 680, 190));

        btnRegresar.setText("Regresar al menu");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 480, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel3.setText("Añadir producto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        lblProducto.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        lblProducto.setText("Producto");
        getContentPane().add(lblProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        lblPrecio.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        lblPrecio.setText("Precio");
        getContentPane().add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        lblCategoria.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        lblCategoria.setText("Categoria");
        getContentPane().add(lblCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        cmbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 120, 30));

        lblMarca.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        lblMarca.setText("Marca");
        getContentPane().add(lblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        lblTalla.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        lblTalla.setText("Talla");
        getContentPane().add(lblTalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, -1));

        cmbMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(cmbMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 120, 30));

        cmbTalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTallaActionPerformed(evt);
            }
        });
        getContentPane().add(cmbTalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 120, 30));

        btnAgregarProducto.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        btnAgregarProducto.setText("Agregar Producto");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        txtProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductoActionPerformed(evt);
            }
        });
        getContentPane().add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 140, 30));
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 140, 30));

        lblBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uam/pds/proyecto/images/Plantilla para historia de instagram fondo femenino rosado.png"))); // NOI18N
        getContentPane().add(lblBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    public void registrarProducto(Producto descripcion){
    System.out.println("Los datos de la persona son: ");
    System.out.println(descripcion.toString());
    }
    
    
    
    public void llenarListaEstados(){
     UtileriaLineaVenta administrar = new UtileriaLineaVenta();
     List<String>listaC = administrar.llenarListaCategoria();
     List<String>listaM = administrar.llenarListaMarcas();
     List<String>listaT = administrar.llenarListaTalla();
     
     

     
     for(int i=0;i<listaC.size();i++){
         String cat = listaC.get(i);
         cmbCategoria.addItem(cat);
        }
     
     for(int i=0;i<listaM.size();i++){
         String mar = listaM.get(i);
         cmbMarca.addItem(mar);
        }
     
     for(int i=0;i<listaT.size();i++){
         String talla = listaT.get(i);
         cmbTalla.addItem(talla);
        }
     
    }
    
    


public void agregarLinea(String Categoria,String Talla,String Marca){
System.out.println("aqui va el nombre: ");
 try {
            
          
            
            PreparedStatement pps2 = cn.prepareStatement("insert into Producto(nombre, precio, Categoria_idCategoria,Talla_idTalla,Marca_idMarca) values(?,?,?,?,?)");
            
            
            pps2.setString(1, txtProducto.getText());
            pps2.setString(2, txtPrecio.getText());
            pps2.setString(3, Categoria);
            pps2.setString(4, Talla);
            pps2.setString(5, Marca);
            pps2.executeUpdate();
            JOptionPane.showMessageDialog(null, "Datos linea guardados");
        } catch (SQLException ex) {
            Logger.getLogger(AltasProductosFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
}

public void imprimeLista(List<Producto> lista){
    String listaCompleta= "";
    Iterator iter = lista.iterator();
    
    while(iter.hasNext()){
        Producto linea = (Producto) iter.next();
        listaCompleta = listaCompleta +"\n"+linea.toString();
        
    }
    
    txtResultados.setText(listaCompleta);
    
    }



public void limpiar(){

    
    cmbCategoria.removeAllItems();
    cmbMarca.removeAllItems();
    cmbTalla.removeAllItems();
    txtProducto.setText("");
    txtPrecio.setText("");
    txtProducto.setText("");
    }

public void Iniciar(){
        limpiar();
        llenarListaEstados();
        
        List <Producto> listaProducto = UtileriaLineaVenta.recuperaProducto();
        UtileriaLineaVenta.imprimeListaProducto(listaProducto);
        txtResultados.setText(UtileriaLineaVenta.imprimeListaProducto(listaProducto));
        System.out.println(listaProducto.toString());
        imprimeListaProducto(listaProducto);
        
        
}

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
           mostrarElementos();     
           Iniciar();
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

     public void mostrarElementos(){
        
        int indiceC = cmbCategoria.getSelectedIndex()+1;
        int indiceT = cmbTalla.getSelectedIndex()+1;
        int indiceM = cmbMarca.getSelectedIndex()+1;
        if(indiceC !=0 &&indiceT !=0 &&indiceM !=0 ){
             
    String indiceSC= String.valueOf(indiceC);
    String indiceST= String.valueOf(indiceT);
    String indiceSM= String.valueOf(indiceM);
    
    
    
    
        agregarLinea(indiceSC,indiceST,indiceSM);
        
        
       
        }else{
         
        }
     
     }
    
    
    
    
    private void cmbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCategoriaActionPerformed

    private void cmbMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMarcaActionPerformed

    private void cmbTallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTallaActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
MenuFrm menu = new MenuFrm();
            this.dispose();
            menu.setVisible(true);
            
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltasProductosFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltasProductosFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltasProductosFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltasProductosFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltasProductosFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JComboBox<String> cmbMarca;
    private javax.swing.JComboBox<String> cmbTalla;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblBackGround;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblTalla;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JScrollPane sclProductos;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextArea txtResultados;
    // End of variables declaration//GEN-END:variables
}
