/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uam.patrones.proyecto.formas;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.LinkedList;
import java.util.List;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import uam.patrones.proyecto.clases.Alumno;
import uam.patrones.proyecto.clases.Producto;
import uam.patrones.proyecto.compartido.Compartido;

import uam.patrones.proyecto.operaciones.LlenadoListas;
import uam.patrones.proyecto.operaciones.OperacionesLista;
import uam.patrones.proyecto.operaciones.UtileriaLineaVenta;
import static uam.patrones.proyecto.operaciones.UtileriaLineaVenta.imprimeListaProducto;

/**
 *
 * @author elimanaseszacariasperez
 */
public class ConsultaFrm extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaFrm
     */
    public ConsultaFrm() {
        initComponents();
        Iniciar();
        llenarLista();
        datosCuestionario();
        
    }
    
    public void limpiar(){
    cmbListaSencilla.removeAllItems();
    txtIntroduce.setText("");
    txtResultado.setText("");

    }
    
    
    
    public void Iniciar(){
        limpiar();
        lblNombre.setText(Compartido.nombreUsuario);
        List <Producto> listaProducto = UtileriaLineaVenta.recuperaProducto();
        UtileriaLineaVenta.imprimeListaProducto(listaProducto);
        txtResultado.setText(UtileriaLineaVenta.imprimeListaProducto(listaProducto));
        System.out.println(listaProducto.toString());
        imprimeListaProducto(listaProducto);
        
        
}
    
    private void datosCuestionario(){
        lblNombre.setText(Compartido.nombreUsuario);
        lblInstrucciones.setText("Escoge el tipo de consulta que deseas realizar");
    lblIntroduce.setText("Escribe lo que deseas consultar: ");
   
    
    
    }
    

    
    public void llenarLista(){
    
    LlenadoListas llenado = new LlenadoListas();
    LinkedList<String>lista = llenado.llenarLista();
    
    for(int i=0; i<lista.size();i++){
        cmbListaSencilla.addItem(lista.get(i));
    }
    
    }
    
   
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        cmbListaSencilla = new javax.swing.JComboBox<>();
        lblInstrucciones = new javax.swing.JLabel();
        lblIntroduce = new javax.swing.JLabel();
        txtIntroduce = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        ScrllResultado = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        lblBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setText("Bienvenido");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        lblNombre.setText("jLabel1");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 6, -1, -1));

        cmbListaSencilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbListaSencillaActionPerformed(evt);
            }
        });
        getContentPane().add(cmbListaSencilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 75, -1, -1));

        lblInstrucciones.setText("jLabel1");
        getContentPane().add(lblInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 47, -1, -1));

        lblIntroduce.setText("jLabel2");
        getContentPane().add(lblIntroduce, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        txtIntroduce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIntroduceActionPerformed(evt);
            }
        });
        getContentPane().add(txtIntroduce, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 141, -1));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, -1, -1));

        jButton1.setText("Regresar al Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 610, -1, -1));

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        ScrllResultado.setViewportView(txtResultado);

        getContentPane().add(ScrllResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 743, 481));

        lblBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uam/pds/proyecto/images/Plantilla para historia de instagram fondo femenino rosado.png"))); // NOI18N
        getContentPane().add(lblBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbListaSencillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbListaSencillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbListaSencillaActionPerformed

    private void txtIntroduceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIntroduceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIntroduceActionPerformed

    
    public void Consulta(String nombre,int opc){
        limpiar();
        lblNombre.setText(Compartido.nombreUsuario);
        List <Producto> listaProducto = UtileriaLineaVenta.recuperaProductoConsulta(nombre,opc);
        UtileriaLineaVenta.imprimeListaProducto(listaProducto);
        txtResultado.setText(UtileriaLineaVenta.imprimeListaProducto(listaProducto));
        System.out.println(listaProducto.toString());
        imprimeListaProducto(listaProducto);
        
        llenarLista();
        datosCuestionario();
        
}
    
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
    
        
        
        int indiceSeleccionado = cmbListaSencilla.getSelectedIndex();
    System.out.println(indiceSeleccionado);
    String variable = txtIntroduce.getText();
    System.out.println(variable);
    
    Consulta(variable,indiceSeleccionado);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MenuFrm menu = new MenuFrm();
            this.dispose();
            menu.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrllResultado;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbListaSencilla;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblBackGround;
    private javax.swing.JLabel lblInstrucciones;
    private javax.swing.JLabel lblIntroduce;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtIntroduce;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
