/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uam.patrones.proyecto.formas;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.LinkedList;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import uam.patrones.proyecto.clases.Usuario;
import uam.patrones.proyecto.operaciones.OperacionesLista;
import uam.patrones.proyecto.operaciones.ValidarUsuario;
import static uam.patrones.proyecto.compartido.Compartido.listaUsuario;

/**
 *
 * @author elimanaseszacariasperez
 */
public class LoginFrm extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrm
     */
    public LoginFrm() {
        initComponents();
        leerU("validacion.txt",listaUsuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        btnValidar = new javax.swing.JButton();
        pwdPassword = new javax.swing.JPasswordField();
        btnSalir = new javax.swing.JButton();
        lblBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        lblTitulo.setText("Bienvenido");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        lblLogin.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        lblLogin.setText("Usuario");
        jPanel1.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 241, -1));

        lblPassword.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        lblPassword.setText("Password");
        jPanel1.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        btnValidar.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        btnValidar.setText("Validar");
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });
        jPanel1.add(btnValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, -1, -1));
        jPanel1.add(pwdPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 241, -1));

        btnSalir.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        lblBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uam/pds/proyecto/images/Plantilla para historia de instagram fondo femenino rosado.png"))); // NOI18N
        jPanel1.add(lblBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed

        
        Usuario usr = new Usuario();
        char [] pwd = pwdPassword.getPassword();
        String password = new String(pwd);
        String login = txtUsuario.getText();
      //  usr.setLogin(login);
      // usr.setPassword(password);
        
        validarUsuario(listaUsuario,login, password);
        //mostrarUsrm(listaUsuario, login, password);
       
    }//GEN-LAST:event_btnValidarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

    System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void validarUsuario(LinkedList listaUsr,String login, String pas){
        
        
        
        ValidarUsuario validar = new ValidarUsuario();
        boolean resultado = validar.validarUsuario(listaUsr,login, pas);
        
        if(resultado){
            MenuFrm menu = new MenuFrm();
            this.dispose();
            menu.setVisible(true);
            
            
        }else{
            JOptionPane.showMessageDialog(this, "El Login o Password son incorrectos", "Validación Incorrecta", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    
    public void mostrarUsrm(LinkedList lista, String login, String pas){
    OperacionesLista op = new OperacionesLista();
     int posicion;
     
     posicion = buscarU(lista,login, pas);
     
     if(posicion<0){
         
          JOptionPane.showMessageDialog(this, "El Login o Password son incorrectos", "Validación Incorrecta", JOptionPane.ERROR_MESSAGE);
        
   
     }else{
         MenuFrm menu = new MenuFrm();
            this.dispose();
            menu.setVisible(true);
         
  
         //Usuario al = op.regresarUsuario(lista, posicion);
        // System.out.println("los datos del usuario son: \n "+  al.toString());
       
         
         
         
     }
    
    
    }
   
    
    public static int buscarU(LinkedList listaUsr, String login, String pas){
       OperacionesLista op = new OperacionesLista(); 
       int posicion;
       posicion=op.buscarUsuario(listaUsr, login, pas);
       
       return posicion;
   }
    
    
        public static LinkedList leerU(String nombreArchivo,LinkedList lista){
            OperacionesLista op = new OperacionesLista();
        String cadenaLeida = "";
        FileReader fr;
        BufferedReader archivoLectura;
        try {
            fr = new FileReader(nombreArchivo);
            archivoLectura = new BufferedReader(fr);
            //System.out.println("El inventario es: " );
            cadenaLeida= archivoLectura.readLine();

            while(cadenaLeida != null){
               StringTokenizer st = new StringTokenizer(cadenaLeida,",");
               Usuario inv = new Usuario();
               inv.setLogin(st.nextToken());
               inv.setPassword(st.nextToken());

               
                lista.add(inv);
               System.out.println(inv.toString());
            
             
           cadenaLeida = archivoLectura.readLine();
           
            }
            archivoLectura.close();
        } catch (FileNotFoundException ex) {
          //  Logger.getLogger(Lectura.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("NO FUNCIONA");
        } catch (IOException ex) {
           // Logger.getLogger(Lectura.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("NO FUNCIONA2");
        }
       return lista; 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnValidar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackGround;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
