/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uam.patrones.proyecto.formas;


import java.util.ArrayList;
import java.util.List;
import java.sql.*;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import uam.patrones.proyecto.clases.LineaDeVenta;
import uam.patrones.proyecto.clases.Producto;
import uam.patrones.proyecto.operaciones.EstrategiaDescuentoSobreUmbral;
import uam.patrones.proyecto.operaciones.EstrategiaPreciosVenta;
import uam.patrones.proyecto.operaciones.UtileriaLineaVenta;
import uam.patrones.proyecto.operaciones.Venta;
import uam.patrones.proyecto.operaciones.conexionBD;


/**
 *
 * @author ELI ZACARIAS
 */
public class Principal extends javax.swing.JFrame {
    
    
    
    conexionBD con = new conexionBD();
    Connection cn= con.conexion();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
        Iniciar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        cmbProducto = new javax.swing.JComboBox<>();
        txtCantidad = new javax.swing.JTextField();
        lblCantidad = new javax.swing.JLabel();
        btnAgregarLinea = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblTotalS = new javax.swing.JLabel();
        lblTotalC = new javax.swing.JLabel();
        sclProductos = new javax.swing.JScrollPane();
        txtResultados = new javax.swing.JTextArea();
        btnRegresar = new javax.swing.JButton();
        btnPagar = new javax.swing.JButton();
        lblBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel4.setText("Añadir Linea de Captura");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        cmbProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProductoActionPerformed(evt);
            }
        });
        getContentPane().add(cmbProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 130, 30));

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 130, 30));

        lblCantidad.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        lblCantidad.setText("Cantidad");
        getContentPane().add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        btnAgregarLinea.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        btnAgregarLinea.setText("Agregar Linea de captura");
        btnAgregarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLineaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel1.setText("Producto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo.setText("Producto            Precio             Cantidad              Subtotal            ");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        lblTotalS.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        lblTotalS.setText("Total");
        getContentPane().add(lblTotalS, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 144, 34));

        lblTotalC.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        lblTotalC.setText("Total con descuento");
        getContentPane().add(lblTotalC, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, 190, 34));

        txtResultados.setColumns(20);
        txtResultados.setRows(5);
        sclProductos.setViewportView(txtResultados);

        getContentPane().add(sclProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 674, 176));

        btnRegresar.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        btnRegresar.setText("Regresar al menu");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 190, -1));

        btnPagar.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        btnPagar.setText("Pagar Linea de Captura");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, -1, 34));

        lblBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uam/pds/proyecto/images/Plantilla para historia de instagram fondo femenino rosado.png"))); // NOI18N
        getContentPane().add(lblBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    public void registrarProducto(Producto descripcion){
    System.out.println("Los datos de la persona son: ");
    System.out.println(descripcion.toString());
    }
    
    
    
    public void llenarListaEstados(){
     UtileriaLineaVenta administrar = new UtileriaLineaVenta();
     List<String>lista = administrar.llenarListaProductos();
     
     for(int i=0;i<lista.size();i++){
         String prod = lista.get(i);
         cmbProducto.addItem(prod);
        }
     
    }
    
    

public void agregarLinea(String a){
System.out.println("aqui va el nombre: "+a);
 try {
            
          
            
            PreparedStatement pps2 = cn.prepareStatement("insert into LineaVenta(cantidad, Producto_idProducto) values(?,?)");
            
            
            pps2.setString(1, txtCantidad.getText());
            pps2.setString(2, a);
            pps2.executeUpdate();
            JOptionPane.showMessageDialog(null, "Datos linea guardados");
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
}

public void imprimeLista(List<LineaDeVenta> lista){
    String listaCompleta= "";
    Iterator iter = lista.iterator();
    
    while(iter.hasNext()){
        LineaDeVenta linea = (LineaDeVenta) iter.next();
        listaCompleta = listaCompleta +"\n"+linea.toString();
        
    }
    
    txtResultados.setText(listaCompleta);
    
    }

public void imprimeTotal(){
     Venta unaVenta;
EstrategiaPreciosVenta unaEstrategia;
unaEstrategia = new EstrategiaDescuentoSobreUmbral();
unaVenta = new Venta(unaEstrategia);

float total= unaVenta.obtenerTotalAntesDesc();
float totalF=unaVenta.obtenerTotal();
lblTotalS.setText("Subtotal: "+Float.toString(total));
lblTotalC.setText("Total: " +Float.toString(totalF));
System.out.println (unaVenta.obtenerTotalAntesDesc());
        System.out.println(unaVenta.obtenerTotal());
    
    }
public void imprimePrecio(){
     Venta unaVenta;
EstrategiaPreciosVenta unaEstrategia;
unaEstrategia = new EstrategiaDescuentoSobreUmbral();
unaVenta = new Venta(unaEstrategia);

float total= unaVenta.obtenerTotalAntesDesc();
float totalF=unaVenta.obtenerTotal();

JOptionPane.showMessageDialog(null, "Cantidad a Pagar: "+total +"\n Descuento con el hot sale: "+totalF+"\n Vuelva Pronto :D ");
    }


public void limpiar(){

    cmbProducto.removeAllItems();
    txtCantidad.setText("");
    }

public void Iniciar(){
        limpiar();
        llenarListaEstados();
        
        List <LineaDeVenta> listaVenta = UtileriaLineaVenta.recuperaLineaVenta();
        UtileriaLineaVenta.imprimeLista(listaVenta);
        

        imprimeLista(listaVenta);
        imprimeTotal();
        
        
         Venta unaVenta;
EstrategiaPreciosVenta unaEstrategia;
//DescripcionDeProducto descripcion = new DescripcionDeProducto ("1", Producto, (float) Preciof);
        
//List <DescripcionDeProducto> elementos = new ArrayList<>();

unaEstrategia = new EstrategiaDescuentoSobreUmbral();
unaVenta = new Venta(unaEstrategia);
//unaVenta.ingresarLineaDeVenta(cantidadi, descripcion,((Float)(cantidadi*Preciof)));

//registrarProducto(descripcion);

System.out.println (unaVenta.obtenerTotalAntesDesc());
        System.out.println(unaVenta.obtenerTotal());
        
        
}

    private void btnAgregarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLineaActionPerformed
            mostrarElementos();   
            Iniciar();// TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarLineaActionPerformed

     public void mostrarElementos(){
        
        int indice = cmbProducto.getSelectedIndex()+1;
        
        if(indice !=0){
             
    String indiceS= String.valueOf(indice);
        agregarLinea(indiceS);
        
       
        }else{
         
        }
     
     }
    
    
    
    
    private void cmbProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductoActionPerformed
//DescripcionDeProducto producto= (DescripcionDeProducto)cmbProducto.getSelectedItem();
        
        //prueba
        //System.out.println(estado.getNombre());
        //System.out.println(estado.getClave());
        
        
        
        //mostrarElementos();        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProductoActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        MenuFrm menu = new MenuFrm();
        this.dispose();
        menu.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
                    
        imprimePrecio();
        eliminarRegistros();
                    Iniciar();
    }//GEN-LAST:event_btnPagarActionPerformed

    public void eliminarRegistros(){
    
    PreparedStatement pre = null;
    String query = "TRUNCATE TABLE LineaVenta";
    try{
    pre = cn.prepareStatement(query);
    pre.executeUpdate();
    }catch(Exception e){
    
    System.out.println("No se cargo el pago de la linea de captura");
    }

    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarLinea;
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblBackGround;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotalC;
    private javax.swing.JLabel lblTotalS;
    private javax.swing.JScrollPane sclProductos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextArea txtResultados;
    // End of variables declaration//GEN-END:variables
}
